version: '3.1'
services:
    redis:
        image: 'redis:alpine'
        command: redis-server --requirepass EmpireRedis2021!
    application:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
